# OptiFitACi test script -- 1 grouping variable ================================
#
# This is an example R script (commands) for the use of function 'fitacis4' in
# the OptiFitACi library when ONE input variable (column) is used to identify
# each experiment. In the test case that variable is named 'Ident' with a unique
# value for all A/Ci measurements in each experiment.
#
# The leaf CO2 exchange dataset generated by (derived from) the Li-Cor is the
# file:  "TestCotton_1group.csv", with '1group' referring to use of one grouping
# variable to identify each A-Ci experiment/dataset
#
# To use this program/script, the input test dataset should be copied to the
# Windows directory 'C:/Test/', creating
#
#    "C:/Test/TestCotton_1group.csv"
#
# The input data provides five measured variables, labeled with 'column'
# headings (names) as follows (columns can be in any order):
#
#   Photo  : measured CO2 exchange (umol CO2 m-2 s-1)
#   Ci     : Ci (ppm; umol mol-1)
#   Tleaf  : leaf temperature (degrees Celsius))
#   PARi   : incident PPFD (umol photons m-2 s-1)
#   Press  : atmospheric pressure (kPa)
#
#   Rd is not included in the input dataset and 'useRd = FALSE' is specified
#   in 'fitacis4' (default) so Rd is calculated by the fitting routine
#
# The 'testCotton_1group.csv' file can be downloaded from:
#
#   https://github.com/jsamthor/OptiFitACi/tree/master/R
#
# All output will be written to the same directory (folder) from which the
# input data are read: "C:/Test/"
#
# If "Rtools" has NOT been installed on this computer, which is probably the
# case, install it from the url below (OTHERWISE SKIP). The installation may
# take some minutes. Choose a recent version of Rtools [maybe "(R-release)" but
# not "(R-devel)"] and follow the instructions for installation from the
# "Rtools installer" at this url
#
#    https://cran.r-project.org/bin/windows/Rtools/
#
# Please note that in R uppercase and lowercase letters have different meanings
# so 'Photo' is not the same as 'photo'...you must be careful about that. In
# general though, single quotes (') and double quotes (") are interchangeable
# but use the same one to start and end a character string
#-------------------------------------------------------------------------------

# NOTE that the first instruction below will clear all objects from the R
# workspace so if you have other things in the workspace you'd like to retain,
# SKIP THIS LINE

  rm(list=ls())

# IF these required packages are NOT already installed, install them now,
# OTHERWISE SKIP THIS 'install.packages' program block of five instructions and
# load the libraries in the next block.
#
# Installation of packages is generally only needed once for a
# specific/individual computer. When installing packages, you will be asked for
# site to download from; it might help to choose one 'nearby'. The installation
# process will write a lot messages (e.g., "Installing package into 'C:\__blah'"
# and "trying URL 'https://__blahblah__", just wait until everything has stopped
# with a single  ">"  prompt displayed

  install.packages("usethis")
  install.packages("tidyverse")
  install.packages("devtools")
  install.packages("plantecophys")
  install.packages("plantecowrap") # Needed for utilities such as 'acisummary'

# Load libraries (from previously installed packages). Do not be concerned if
# you are told 'dplyr' is masking 'filter' and 'lag' in the stats library when
# "library(tidyverse)" is executed

  library(usethis)
  library(devtools)
  library(tidyverse)
  library(minpack.lm)
  library(ggplot2)
  library(tidyr)
  library(plantecophys)
  library(plantecowrap)            # Needed for utilities such as 'acisummary'

# Install package "OptiFitACi". If "jsamthor/OptiFitACi" has previously been
# installed on the computer in use, this 'install_github' step can be skipped
# and you can go directly to the "library(OptiFitACi)" line/instruction below
#
# To use install_github below (or anywhere else), "library(devtools)" MUST have
# been loaded above
#
# If you previously installed "jsamthor/OptiFitACi" and ask to install it again,
# but it has not been updated since the last time you installed it, you should
# receive a message like: "Skipping install of 'OptiFitACi' from a github
# remote, the SHA1 (d1a5344c) has not changed since last install. Use
# `force = TRUE` to force installation". That's all fine; just ignore the
# message and proceed

  install_github("jsamthor/OptiFitACi")

#### A message like this may appear:

     #->  These packages have more recent versions available.
     #->  It is recommended to update all of them.
     #->  Which would you like to update?

     #->  1: All                          
     #->  2: CRAN packages only           
     #->  3: None                         
     #->  4: rlang (1.0.5 -> 1.0.6) [CRAN]
     #->  5: cli   (3.4.0 -> 3.4.1) [CRAN]
     #->  6: vctrs (0.4.1 -> 0.4.2) [CRAN]

     #->  Enter one or more numbers, or an empty line to skip updates:

#### IF SUCH A MESSAGE IS RETURNED FROM R, enter a blank line <enter/return> or
#### one of the numbers [1 through 6 in this example, but other instances will
#### produce different numbers/lists] BEFORE PROCEEDING FURTHER

# Now load the OptiFitACi library to gain access to the 'fitacis4' function

  library(OptiFitACi)

# At this point all the required software should be available to the R session
#
# Now set the working directory to the directory (folder) with the data, and
# that will contain the output ('c:/test' in this example). The test dataset is
# in the file 'TestCotton_1group.csv' as outlined in the header comments above.
# It will be referred to as "testd" (test data) in this program/script

  setwd("c:/Test")
  testd = read.csv("TestCotton_1group.csv")

# Display the data structure using function 'str' to check that all is as
# expected, i.e., that all the dataset variables are present and the first
# several values listed are correct (or look reasonable anyway) -- this only
# displays snippets of the input data, not the full dataset

  str(testd)              

# For this test we are making sure that the components of the 'ID' variable
# are all of categorical type (i.e., they are of 'factor' type). In the test
# dataset there are 30 A/Ci experiments composed of five plants (reps) each
# measured at six temperatures with 10 Ci values per plant-temperature
# combination, for a total of 300 A-Ci combinations. The input variable 'Ident'
# is unique for each plant-temperature combination (each A-Ci curve fit).
# For example, Ident of 40_Sicot_3 means when we call fitacis4 all rows with
# that Ident will be grouped into a single A/Ci analysis (in this case the 3rd
# replicate of a 'Sicot' plant in a 40-degree Celsius experiment)

  testd$Ident = as.factor(testd$Ident)

# We will make a variable associated with Ident that is sorted so it can later
# be substituted for ID. The functions/utilities in 'plantecophys' and
# 'plantecowrap' sort the input data in 'ascending' order by grouping
# variables(s), so the 'order' below is important

  IDin = unique(testd$Ident[order(testd$Ident)])

# NOW FOR THE A-Ci fitting for each experiment (or replicate), specifying a
# quadratic fit of mesophyll conductance to temperature. The coefficients
# gm_coef0, gm_coef1, and gm_coef2 are the same as the default (the fitacis4
# default is based on the data in the test dataset), but we will enter them
# anyway to illustrate the approach if a different gm-versus-temperature
# quadratic equation is to be used with other datasets. Other parameter/variable
# values are entered to match results from the cotton experiments,
# overwriting/replacing the default values. Some of the default values are taken
# from function 'fitaci' in R package plantecophys.
#
# The OptiFitACi function 'fitacis4' below calls the plantecophys function
# 'fitaci,' but with greater flexibility and control over biochemical parameters
# and their values, including responses to temperature. When using the quadratic
# equation to represent the response of mesophyll conductance (gm) to
# temperature (Tleaf) be sure to use enough (all significant) digits in the
# equation coefficients. The values derived from the cotton experiments are:
#
#     gm_coef0 = 0.571, gm_coef1 = -0.0090, gm_coef2 = 0.000355
#
# The other variables used here are described in the Plant, Cell & Environment
# article. With this use of 'fitacis4' most of the default parameter values are
# applied. The output from the analysis is saved in 'fits1', which can be named
# anything (i.e., any valid R name)
#
# This step may take a few seconds

  fits1 = fitacis4 (testd,
                    group1 = "Ident",
                    gm_method = "Quad",
                    gm_coef0 = 0.571, gm_coef1 = -0.0090, gm_coef2 = 0.000355,
                    K25 = 541.47, Ek = 53.03, Gstar25 = 39.98, Egamma = 28.11)

# At this point the analysis is complete (if above is successful without error
# messages). Now we'll save and plot the results for inspection and further use
#
# Here the ACi parameter information is stored in 'Opti_out', which is also
# written to a text (.csv) file. 'acisummary' is a utility function in package
# 'plantecowrap'. In the case below the output is written to the file
# 'c:/Test/OptiFitACi_test_kinetics_out_group1.csv', which is an
# implicit concatenation of the working directory (from 'setwd' above) and the
# filename 'OptiFitACi_test_kinetics_out_group1.csv' defined with 'file =' in
# the 'write.csv' argument list below (the 'fits1' in 'fits = fits1' below is
# from 'fits1 = fitacis4 (testd, ...' above

  Opti_out = acisummary(data = testd, fits = fits1, group1 = "Ident")
  Opti_out$ID = IDin
  write.csv(Opti_out, file = 'OptiFitACi_test_kinetics_out_1group.csv',
            row.names = F)

# Now open (create) a file ('OptiFitACi_test_plots_1group.pdf') to contain plots
# of the output for each replicate (using system defaults for pdf file
# parameters here). This is for visual inspection of data and results. The
# 'par(mar...))' function is used to set the plot margins so they behave well on
# my machine. FYI the default values are 'mar=c(5.1,4.1,4.1,2.1)'. This pdf file
# will be written to the "c:/Test" directory/folder

  pdf("OptiFitACi_test_plots_1group.pdf")  ;  par(mar=c(5.1,5.1,4.1,2.1))

# Add one plot to the pdf file for each replicate (there are "length(fits)"
# replicates -- equals 30 in test dataset), and then close the pdf file
#
# 'i' is the replicate number incremented in a simple "for loop"
# We will get the 'Temperature_Plant_Rep' value for each case from Opti_out$ID
# The '[[' and ']]' instead of '[' and ']' in 'fits1[[i]]' may seem superfluous
# in this case, but is the correct way to refer to a list, so we use it

  for (i in 1:length(fits1)) { plot(fits1[[i]],
                               main = paste0('Experiment ', Opti_out$ID[i])) }

# dev.off() will close (complete and make available) the pdf file

  dev.off() # close the pdf file

# If that is successful, you will receive the message:
#
# "null device"
# "          1"
#
# Other non-fatal possibilities exist, but this is preferred/goal

# Finally, we'll display the full 'fitaci' input/output for experiment 10 on the
# screen, to take a quick look at what happened, with the following 'summary'
# instruction (the '[[' and ']]' instead of '[' and ']' may seem superfluous in
# this case, but it is the correct way to refer to a list in R)

  summary(fits1[[10]])

# Please note that the input Ci values are in units of umol/mol (ppm), but
# the Ci values in 'fits1' and displayed with 'summary(fits1[[10]])' above were
# converted to microbars (ubar) based on the input pressure data (variable
# 'Press')
#
# That's it for the example session.  Check the two files written to 'c:/Test/",
# "C:\Test\OptiFitACi_test_plots_1group.pdf" and
# "C:\Test\OptiFitACi_test_kinetics_out_1group.csv"
